install_area_detection_node:
  ros__parameters:
    depth_topic: "/depth"
    right_topic: "/image_rect"
    vis: true
    shrink_ratio: 0.3
    bracket: # in millimeters
      height: 460
      width: 500
    threshold: # in millimeters
      top: 2500 
      bottom: 1100
